services:
  traefik:
    image: traefik:v3.5
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    build: .
    command: fastapi run app/main.py --port 80 --proxy-headers
    labels:
      - "traefik.http.routers.flipping.rule=Host(`flipping.localhost`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
